module.exports = {
  // Global events
  SUCCESS: "SUCCESS",
  LAYOUT: "LAYOUT",

  // Timer Events
  TIMER_START: "TIMER_START",
  TIMER_STOP: "TIMER_STOP",
  TIMER_DATA: "TIMER_DATA",
  SETTINGS_CHANGED: "SETTINGS_CHANGED",

  //Capture Events
  CAPTURE: "CAPTURE",
  CAPTURE_STOP: "CAPTURE_STOP",
  CAPTURE_DATA: "CAPTURE_DATA",

  //Midi Events
  NOTE_ON: "NOTE_ON",
};
